ANSWER_EXPLANATIONS = {
    "Almond tree": "Almond trees produce almonds inside a tough shell surrounded by a fuzzy green hull.",
    "Ant": "Ants live in colonies where workers share jobs like finding food and caring for young.",
    "Apple tree": "Apple trees grow blossoms first, and those flowers can turn into fruit after pollination.",
    "Apricot tree": "Apricot trees grow orange stone fruits with a single hard pit inside.",
    "Avocado tree": "Avocado trees grow large green fruits that each contain one big seed.",
    "Bald eagle": "Bald eagles are strong fish-eating birds and are a national symbol of the United States.",
    "Banana tree": "Banana plants look like trees, but their trunk-like stem is made from tightly wrapped leaves.",
    "Bark": "Bark protects a tree's trunk from weather, insects, and injury.",
    "Bee": "Bees help plants grow by moving pollen between flowers as they collect nectar.",
    "Beetle": "Beetles have hardened front wings that protect their flying wings underneath.",
    "Birch tree": "Birch trees often have pale, papery bark that peels in thin layers.",
    "Bird": "Birds are feathered animals, and most species lay hard-shelled eggs.",
    "Branch": "Branches spread from a tree trunk and hold leaves, flowers, and fruit.",
    "Butterfly": "Butterflies start life as caterpillars before changing inside a chrysalis.",
    "Calf": "A calf is a young cow and usually stays close to its mother for milk and protection.",
    "Camel": "Camels can go long periods without drinking because their bodies conserve water well.",
    "Canary": "Canaries are small songbirds that became popular because of their bright songs.",
    "Cat": "Cats use whiskers to help judge spaces and sense movement close to their face.",
    "Caterpillar": "Caterpillars are the larval stage of butterflies and moths, and many spend their time eating leaves.",
    "Cheetah": "Cheetahs are the fastest land animals over short distances.",
    "Cherry tree": "Cherry trees produce spring blossoms before many varieties grow cherries.",
    "Chestnut tree": "Chestnut trees grow nuts inside spiky green cases called burrs.",
    "Chick": "A chick is a young bird that has recently hatched from an egg.",
    "Chicken": "Chickens are domesticated birds often kept for eggs and meat.",
    "Cockroach": "Cockroaches are hardy insects that can live in many warm, sheltered places.",
    "Cow": "Cows are ruminants, which means they digest grass with a multi-part stomach.",
    "Cricket": "Male crickets make chirping sounds by rubbing their wings together.",
    "Crow": "Crows are very intelligent birds that can remember faces and solve problems.",
    "Date palm": "Date palms grow clusters of sweet dates and thrive in hot climates.",
    "Deer": "Many male deer grow antlers and shed them each year.",
    "Dog": "Dogs have a strong sense of smell and were domesticated from wolves.",
    "Dove": "Doves are often used as symbols of peace because of their gentle image.",
    "Duck": "Ducks have webbed feet that help them paddle through water.",
    "Eagle": "Eagles have sharp talons and excellent eyesight for spotting prey.",
    "Elephant": "Elephants use their trunks to smell, drink, pick up food, and communicate.",
    "Fig tree": "Fig trees produce soft fruit with many tiny seeds inside.",
    "Firefly": "Fireflies make light with a chemical reaction in their bodies.",
    "Fish": "Fish breathe underwater using gills that take oxygen from water.",
    "Flamingo": "Flamingos get their pink color from pigments in the food they eat.",
    "Flea": "Fleas are tiny jumping insects that feed on the blood of animals.",
    "Flowers": "Flowers help many plants reproduce by attracting pollinators and making seeds.",
    "Fly": "Flies taste with sensors on their feet as well as their mouthparts.",
    "Foal": "A foal is a young horse, and many can stand soon after birth.",
    "Forest": "Forests are habitats filled with trees, plants, fungi, and many animals.",
    "Fox": "Foxes have sharp hearing and often hunt small animals at dawn or dusk.",
    "Frog": "Frogs absorb water through their skin and often start life as tadpoles.",
    "Giraffe": "Giraffes use their long necks to reach leaves high in trees.",
    "Goat": "Goats are agile climbers and can browse leaves, shrubs, and grasses.",
    "Goose": "Geese are social waterbirds and often fly in V-shaped formations.",
    "Grapefruit tree": "Grapefruit trees are citrus trees that grow large tangy fruits.",
    "Grasshopper": "Grasshoppers use powerful back legs to leap away from danger.",
    "Green": "Green leaves contain chlorophyll, which helps plants use sunlight for energy.",
    "Hawk": "Hawks are birds of prey with strong vision and curved beaks.",
    "Hazelnut tree": "Hazelnut trees produce small round nuts inside leafy husks.",
    "Horse": "Horses can sleep standing up thanks to a locking system in their legs.",
    "Hummingbird": "Hummingbirds beat their wings very quickly and can hover in place.",
    "Insect": "Insects have six legs and a body split into three main parts.",
    "Kangaroo": "Kangaroos move by hopping and carry young joeys in a pouch.",
    "Kitten": "A kitten is a young cat and is born with closed eyes.",
    "Ladybug": "Ladybugs often eat aphids, which makes them helpful in gardens.",
    "Lamb": "A lamb is a young sheep and is usually covered in soft wool.",
    "Leaves": "Leaves make food for plants through photosynthesis.",
    "Lemon tree": "Lemon trees are citrus trees that grow sour yellow fruit.",
    "Lime tree": "Lime trees grow small green citrus fruits with a sharp flavor.",
    "Lion": "Lions live in social groups called prides.",
    "Mango tree": "Mango trees grow sweet tropical fruits with one large flat seed.",
    "Maple tree": "Maple trees are known for colorful autumn leaves and sugary sap.",
    "Monkey": "Many monkeys use their hands and tails to move through trees or handle food.",
    "Mosquito": "Only female mosquitoes bite because they need nutrients for their eggs.",
    "Moth": "Many moths are active at night and are drawn to bright lights.",
    "Mouse": "Mice have sharp front teeth that keep growing throughout their lives.",
    "Oak tree": "Oak trees produce acorns, which feed squirrels, birds, and other wildlife.",
    "Olive tree": "Olive trees can live for hundreds of years and grow fruit used to make olive oil.",
    "Orange tree": "Orange trees are evergreen citrus trees that grow sweet orange fruit.",
    "Ostrich": "Ostriches cannot fly, but they can run very fast on strong legs.",
    "Owl": "Owls have soft-edged feathers that help them fly quietly.",
    "Oxygen": "Plants release oxygen during photosynthesis, helping animals breathe.",
    "Palm tree": "Many palm trees grow in warm places and have large fan or feather-shaped leaves.",
    "Panda": "Pandas eat mostly bamboo, even though they belong to the bear family.",
    "Parrot": "Parrots are clever birds, and some can mimic human speech.",
    "Peach tree": "Peach trees grow fuzzy stone fruits with a hard pit inside.",
    "Peacock": "Male peafowl, called peacocks, display colorful tail feathers to attract mates.",
    "Pear tree": "Pear trees grow sweet fruits that ripen from flowers after pollination.",
    "Penguin": "Penguins are flightless birds that use their wings like flippers in water.",
    "Pig": "Pigs are intelligent animals with a strong sense of smell.",
    "Pigeon": "Pigeons are strong flyers and can find their way home from far away.",
    "Pine tree": "Pine trees are evergreens that grow needles and cones.",
    "Plum tree": "Plum trees grow smooth-skinned stone fruits with juicy flesh.",
    "Polar bear": "Polar bears have thick fur and fat to help them survive Arctic cold.",
    "Puppy": "A puppy is a young dog and depends on its mother when it is very young.",
    "Rabbit": "Rabbits have long ears and strong back legs for quick hopping.",
    "Red": "Some autumn leaves turn red when sugars are trapped in the leaf as chlorophyll fades.",
    "Redwood tree": "Redwood trees are among the tallest trees on Earth.",
    "Robin": "Robins are often recognized by their reddish-orange breast.",
    "Rooster": "Roosters are male chickens and are known for crowing.",
    "Roots": "Roots anchor plants in the ground and take in water and minerals.",
    "Seagull": "Seagulls are coastal birds that often eat fish and scraps.",
    "Seeds": "Seeds contain baby plants and stored food to help them start growing.",
    "Sheep": "Sheep grow woolly coats that can be sheared and spun into yarn.",
    "Shelter": "Trees provide shelter for animals by offering nesting places, shade, and protection.",
    "Silkworm": "Silkworms spin cocoons made of silk fibers.",
    "Skunk": "Skunks can spray a strong-smelling liquid to defend themselves.",
    "Small bird": "Small birds often need lots of food because their bodies use energy quickly.",
    "Snake": "Snakes smell with their tongues by collecting scent particles from the air.",
    "Sparrow": "Sparrows are small birds often seen hopping near people and buildings.",
    "Squirrel": "Squirrels bury nuts and seeds, and some forgotten seeds can grow into trees.",
    "Stork": "Storks are long-legged birds often seen near wetlands.",
    "Sunlight": "Plants use sunlight as energy to make food through photosynthesis.",
    "Swan": "Swans are large waterbirds with long necks and strong pair bonds.",
    "Termite": "Termites break down wood and plant material, recycling nutrients into soil.",
    "Tiger": "Tigers are striped big cats, and each tiger's stripe pattern is unique.",
    "Tortoise": "Tortoises live on land and carry a hard protective shell.",
    "Trunk": "A tree trunk supports branches and carries water between roots and leaves.",
    "Turkey": "Turkeys are large ground birds native to North America.",
    "Turtle": "Turtles have protective shells made from bone.",
    "Walnut tree": "Walnut trees grow edible nuts inside hard shells and green outer husks.",
    "Wasp": "Wasps can help control other insect populations and some also pollinate flowers.",
    "Water": "Water helps move nutrients through plants and keeps their cells firm.",
    "Whale": "Whales are mammals that breathe air through blowholes.",
    "Willow tree": "Willow trees often grow near water and have flexible branches.",
    "Zebra": "Zebras have black-and-white stripes, and each pattern is different.",
}


def get_explanation(question):
    custom_explanation = question.get("explanation")
    if custom_explanation:
        return custom_explanation

    answer = question.get("answer", "")
    return ANSWER_EXPLANATIONS.get(
        answer,
        f"The clue in this question points to {answer}. Try linking that detail with the answer for next time."
    )
